services:
  backend:
    build:
      context: ./backend
    ports:
      - "4000:4000"
    environment:
      - DB_HOST=mysql
      - DB_USER=root
      - DB_PASSWORD=iit123
      - DB_NAME=authentication
      - MINIO_HOST=minio
      - MINIO_PORT=9000
      - MINIO_USE_SSL=false
      - MINIO_ACCESS_KEY=minio
      - MINIO_SECRET_KEY=minio123
    depends_on:
      - mysql
      - minio

  mysql:
    image: mysql:8.0
    environment:
      MYSQL_ROOT_PASSWORD: root_password
      MYSQL_DATABASE: authentication
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql

  minio:
    image: minio/minio
    command: server /data
    environment:
      MINIO_ROOT_USER: minio
      MINIO_ROOT_PASSWORD: minio123
    ports:
      - "9000:9000"
    volumes:
      - minio_data:/data

  nginx:
    build:
      context: ./nginx
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf  # Use the correct path and filename
    ports:
      - "80:80"
    depends_on:
      - backend

volumes:
  mysql_data:
  minio_data:
